### ISSUE TITLE
ملاحظات واقتراحات

### ISSUE THREAD

**Issue by shabib-m** [drupalsaudi/saudi-distribution#1]
السلام عليكم ورحمة الله 
هذي التوزيعه بذره اساسيه لها فيها نوعين من انواع المحتوى بحث وكتب مع الصفحات والمقالات والحقول ملفات وصور مع العنوان ونص الموضوع مع وحدة Admin Toolbar نقدر نضيف لها اللي نحتاجه مع الانتباه لعدد اعضاء المجتمع مانحتاج نضيف وحدات كثيرة ونتعب في دعمها وتأثر في اداء التوزيعه تستهلك موارد كثيرة من السيرفر حتى ما يكون لها اثر سلبي على مجموعة دروبال ودروبال نفسها 

الاقتراحات =
1- التصميم واضافة شعار المجموعه لها ان كان عند تثبيت التوزيعة او واجهة الموقع واضافة صناديق  اللي تشوفونها مناسبة 
2- صفحة للمساعدة داخل لوحة التحكم ممكن نعملها من الرؤى ونضيف لها صندوق نضيف بداخلة كل اللي تشوفونه مناسب من كلمة عنها توضيحية الى الدروس والشروحات حتى تقديم الدعم للتوزيعة ولمجموعة دروبال 

هذا اللي عندي اللحين واكيد بعض الامور الثانية بتطلع مع النقاش

**Comment by shabib-m** [comment]
ببدى ان شاء الله في تعديل قالب الادارة وصفحة تثبيت دروبال مع اضافة صفحة داخل لوحة التحكم مساعدة واضافة رابط لها في الاختصارات داخل التوزيعة

**Comment by shabib-m** [comment]
تم تعديل الوان صفحة التثبيت مع ترجمة اسم التوزيعة ووصفحها مع اضافة رابط الدعم للتوزيعه هنا
![توزيعة-دروبال-السعودية-صفحة-التثبيت](https://user-images.githubusercontent.com/66571723/84566784-8ceb4400-ad7c-11ea-948b-d54ef29c974e.jpg)

**Comment by shabib-m** [comment]
تم اضافة صفحة المساعدة داخل لوحة التحكم مع ا ضافة رابطها للقائمة مع الاختصارات 
![توزيعة-دروبال-السعودية-صفحة-المساعدة-مع-اضافة الرابط](https://user-images.githubusercontent.com/66571723/84566858-2a467800-ad7d-11ea-8bfd-5c6e7deb70b9.jpg)

**Comment by shabib-m** [comment]
تم بفضل الله تثبيت البلد الافتراضي 
السعودية
المنطقة الزمنية 
الرياض

![توزيعة-دروبال-السعودية-صفحة-التثبيت-البلد الافتراضي-المنطقة-الزمنية](https://user-images.githubusercontent.com/66571723/84797632-b7e6c980-b002-11ea-804d-6c73ba1aa6bb.png)

**Comment by yosriy82** [comment]
السلام عليكم ورحمة الله وبركاته،
مقترح لاضافة :
1. gitignore لالغاء بعض الملفات

2. Settings.php  باعدادات اساسية وشرح لاضافة settings.local.php

3. مرحلة اضافةالمحتوى للصفحة الرئيسية، مثلا، ما تم عمله بخصوص الدور والقائمة الرئيسية يجعل المستخدم مستفيد من تنزيل هذه النسخة..

شكرا جزيلا

**Comment by shabib-m** [comment]
وعليكم السلام ورحمة الله وبركاته 
تم اضافة ملف (gitignore ) للنسختين المستقره ونسخة المطورين
الغريب انها موجوده على جهازي توقعت انه تم رفعها مع الملفات 

ان شاء الله كل الامور اللي تخص التوزيعه بيتم وضعها في الويكي حتى تكون واضحه ويسهل التعامل معها

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
