### ISSUE TITLE
قالب الادارة 

### ISSUE THREAD

**Issue by shabib-m** [drupalsaudi/saudi-distribution#10]
القالب قائم على القالب الافتراضي seven
حتى نحتفظ بالتعديلات وما يتأثر بتحديث النسخه 
الموضوع هذا تعريف بالقالب والاضافات وتعديل الاخطاء مثل rtl 
وغيرها فضلا عند وجود اي خطأ او طلب اضافة او الاستفسار استخدموا الرابط 
https://github.com/drupalsaudi/saudi-distribution/issues/new/choose

**Comment by shabib-m** [comment]
القالب مرفق لكم للتجربه قبل اعتماده 
[drupalsaudi_seven.zip](https://github.com/drupalsaudi/saudi-distribution/files/4933585/drupalsaudi_seven.zip)

**Comment by shabib-m** [comment]
بيتم الاعتماد على قالب claro 
لانه بيكون افتراضي في دروبال 10 من الافضل الاعتماد عليه حتى المستخدم يتعود عليه 
النقاش مفتوح مع العلم القالب افتراضي وموجود في قلب دروبال 8 و 9 
https://www.drupal.org/project/claro

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
