### ISSUE TITLE
فرق التوزيعة (التطوير و الاعمال و التصميم و المحتوى ) 

### ISSUE THREAD

**Issue by al7jy99** [drupalsaudi/saudi-distribution#11]
فريق التطوير :
شبيب - بندر - يُسري - سعود - بندر

فريق الاعمال :
لمى  -عبدالله - يُسري - نواف 

فريق التصميم و (التعريب) : 
رغد - جواهر - __

فريق المحتوى و ( الترجمة ) :
عبدالله عمر و فريقه

**Comment by al7jy99** [comment]
يمكنك اضافة نفسك في اي فريق تريد المجال مفتوح

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
