### ISSUE TITLE
كورسات دروبال

### ISSUE THREAD

**Issue by al7jy99** [drupalsaudi/saudi-distribution#13]
Drupal 8 Beginner's Course:
https://www.youtube.com/watch?v=6e8QyfvQMmU&list=PLpVC00PAQQxHzlDeQvCNDKkyKRV1G3_vT

Drupal 8 Site Building Course:
https://www.youtube.com/watch?v=R1ivRsz_urk&list=PLpVC00PAQQxGwyvUD_tYcBbLJqRC1CZ6U

**Comment by al7jy99** [comment]
Drupal 8 Theming

https://www.youtube.com/watch?v=XOV8VNTAvek&list=PLUBR53Dw-Ef818EUxzNoWKcQ7PYUXpFFA&ab_channel=WatchandLearn

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
