### ISSUE TITLE
تفعيل debug وتعطيل الكاش التخزين المؤقت للقوالب

### ISSUE THREAD

**Issue by shabib-m** [drupalsaudi/saudi-distribution#16]
بما انها نسخة المطورين تم تفعيل 
debug للقوالب 
والتخزين المؤقت الخاص بها ونظام القوالب twig
https://github.com/drupalsaudi/saudi-distribution/commit/f08f07ff45936c0ea36a1c5c5723f7469a5c63de

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
