### ISSUE TITLE
 ترقية نسخة المطورين والوحدات والقالب

### ISSUE THREAD

**Issue by shabib-m** [drupalsaudi/saudi-distribution#17]
تم بفضل الله ترقية  ترقية نسخة المطورين والوحدات والقالب

اتمنى الاهتمام بالتحديثات لقلب دروبال والوحدات والقوالب
ومتابعة تحديثها باستمرار

https://github.com/drupalsaudi/saudi-distribution/commit/6e21a9230d449ee5939a20a2624a3bef7c6c077b
https://github.com/drupalsaudi/saudi-distribution/commit/99f8176d0628dbeec10068fb909e26fe0b00646a
https://github.com/drupalsaudi/saudi-distribution/commit/a6a6904abee3bd46fd4d9b92d2f4f0a6435f3d6c

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
