### ISSUE TITLE
متابعة القالب الافتراضي للتوزيعه

### ISSUE THREAD

**Issue by shabib-m** [drupalsaudi/saudi-distribution#18]
هنا بيكون ان شاء الله متابعة لتطويرات قالب التوزيعه الافتراضي 

من ابداع اخوي بندر

@balharthi 

الاضافات المستخدمة {ممكن نضيف عليها او نستغني عنها بعد اجتماع الاراء عليها}

القوائم =
اضافة الايقونات {}
https://www.drupal.org/project/fontawesome_menu_icons

اضافة مهمة للتحكم في اضافة كلاس انماط للقوائم مميزة لكن للاسف دعمها خارج مجتمع دروبال
https://www.drupal.org/project/menu_link_attributes
اضغطوا على الصورة حتى تتحرك 
https://i.imgur.com/jZCQrnW.gifv?twitter#t

الصناديق =

اضافة فورم للصناديق مدري عن دعمها لكن الاضافه مميزة والفورم ممكن نتحكم في مكان ظهوره من الصناديق الصلاحيات نفسها الموجوده في admin/people/permissions
https://www.drupal.org/project/formblock

تعدد اللغات =

تحتاج وحدة Bootstrap Library 
الا دعم اللغات واعتقد امرها سهل على مبدعين مجموعة دروبال السعودية ويوجد مثال 
https://www.drupal.org/project/bootstrap_library/issues/2951788

لو تحرك الموضوع وتم تطوير الكود بيعتمدونه مطورين الاضافه ونضمن الدعم معها 

السلايد شو عرض الشرائح
https://www.drupal.org/project/views_slideshow

**Comment by shabib-m** [comment]
انتهيت من القائمة العلوية الحمدلله
![menu-top-saudidrupal-theme](https://user-images.githubusercontent.com/66571723/99918144-02910e00-2d26-11eb-9dbe-e4596416ec85.png)

**Comment by shabib-m** [comment]
التحديث الاول

**Comment by shabib-m** [comment]
السلايد شو انتهيت منه الحمدلله 
![Untitled11](https://user-images.githubusercontent.com/66571723/100019186-ac3bd200-2dee-11eb-87d7-ef149b6a9b2a.gif)

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
