### ISSUE TITLE
كورس التعامل مع القوالب 

### ISSUE THREAD

**Issue by al7jy99** [drupalsaudi/saudi-distribution#19]
Drupal 8 Theming
https://www.youtube.com/watch?v=XOV8VNTAvek&list=PLUBR53Dw-Ef818EUxzNoWKcQ7PYUXpFFA&ab_channel=WatchandLearn

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
