### ISSUE TITLE
خطة سير العمل 

### ISSUE THREAD

**Issue by shabib-m** [drupalsaudi/saudi-distribution#2]
السلام عليكم ورحمة الله وبركاته 
هنا بيكون الاولويات وخطة سير العمل وحتى الاضافات المستقبلية 
اتمنى قبل اضافة اي شي هنا يتم مناقشته في الموضوع السابق 
https://github.com/drupalsaudi/saudi-distribution/issues/1

- [x] ~~انشاء التوزيعة~~ 
- [x] ~~صفحة المساعدة داخل لوحة التحكم~~
- [ ] **التصميم للواجهه**
- [ ] **الترجمه**
- [ ] **ادارة الاصدرات للتوزيعة**
- [ ] **الصناديق داخل لوحة التحكم dashboard بسيط يسهل على الادارة التعامل معها**

**Comment by samaphp** [comment]
ماشاء الله .. جهد عظيم الله يبارك فيك
قمت بتركيب التوزيعة على جهازي الشخصي وأعجبني أنها تقوم بضبط وتفعيل بعض الموديولات بشكل تلقائي مثل admin_toolbar وغيره ..

ممكن لزيادة ضبط حماية التوزيعة ممكن نشوف لو نقدر نفعل ونضبط بعض الموديولات مثل:
- Captcha

أيضاً هل ممكن نفعل موديول مثل
Layout builder
بحيث يكون خيار معتمد ومدعوم من تصميم التوزيعة؟
بحيث يسهل على الناس تصميم الصفحات
أعتقد إذا بنعتمده لابد نعتمد استخدام بعض الموديولات المساعدة لجعله يكون أبسط

وشكراً لك على جهودك

**Comment by shabib-m** [comment]
ياهلابك وغلا
كلامك سليم بخصوص
Captcha 
بيتم اضافتها لنسخة المطورين والافضل تفعيلها على اتصل بنا والتسجيل تكون جاهزه مع تثبيت التوزيعه وش رايك وهل فيه اماكن ثانية تحتاجها؟
وممكن نضيف لها 
recaptcha
بدون تفعيل ولا ضبط لانها تحتاج التسجيل في قوقل
بخصوص 
 Layout builder
اللي اشوفه ننتظر اعتماد القالب الافتراضي للتوزيعه اذا احتاجها نفعلها اذا ما استخدمها نتركها

اللحين جالس اشتغل على نظام تسجيل الاعضاء غير الافتراضي حتى نخصصه لاعضاء الجمعيات ونضيف له الحقول المستخدمه في اغلب الجمعيات مع فتح المجال لاضافة الحقول حتى يخصصونها 

شاكر ومقدر اضافتك المميزه

**Comment by samaphp** [comment]
جميل جداً ماشاء الله
أتوقع النماذج المهمة لتفعيل الـ
Captcha
هي النماذج التالية:
- نموذج اتصل بنا
- نموذج التسجيل
- نموذج تسجيل الدخول
- نموذج استعادة كلمة المرور
- وأي نموذج متاح للزوار

وممكن يتم الاكتفاء بإستخدام صورة عشان مايحتاج ضبط من قوقل وتكون فعالة تلقائياً من بداية النظام

**Comment by shabib-m** [comment]
تم الله يسعدك مع التوضيح اتصل بنا فيه للموقع وفيه الخاص باعضاء الموقع الموجود في الملفات الشخصية تم اضافتها لهم الاثنين 
هذي الاعدادات 

- تم ضبط الاعدادات على صورة التحقق افتراضي

وهذي النماذج اللي تم تفعيله عليها 

- اتصل بنا للموقع

- اتصل بنا للاعضاء

- تسجيل الاعضاء

- تسجيل الدخول

- استرجاع كلمة المرور

الاضافه في نسخة المطورين 
https://github.com/drupalsaudi/saudi-distribution/tree/drupalsaudi-dev

git clone -b branch <remote_repo>

**Comment by shabib-m** [comment]
للتعامل مع نسخة المطورين 

https://github.com/drupalsaudi/saudi-distribution/wiki/%D9%86%D8%B3%D8%AE%D8%A9-%D8%A7%D9%84%D9%85%D8%B7%D9%88%D8%B1%D9%8A%D9%86-dev

**Comment by shabib-m** [comment]
جاري ان شاء الله دعم القالب اطار بوتستراب للغه العربية من اليمين الى اليسار
حتى نسهل على المصممين يبدعون مع التوزيعه

**Comment by shabib-m** [comment]
تم اضافة دعم مكتبة 
bootstrap 4 rtl 
الداعمه للغه العربية من اليمين الى اليسار وطبعا غير مفعله مجرد دعم وتوفيرها لمصممين المواقع عند رغبتهم في التصميم

**Comment by yosriy82** [comment]
السلام عليكم ورحمة الله وبركاته،
عمل ممتاز وشغل عالمي 😍👍👍👍
تحياتي للجميع 🤝💚

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
