### ISSUE TITLE
منظمة المشروع

### ISSUE THREAD

**Issue by al7jy99** [drupalsaudi/saudi-distribution#20]
الصورة داخل الاشيو

**Comment by al7jy99** [comment]
![WhatsApp Image 2020-12-26 at 6 35 28 PM](https://user-images.githubusercontent.com/36070864/103155015-f973e080-47ac-11eb-9dce-eabf492290c0.jpeg)

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
