### ISSUE TITLE
خطوات دخول الشخص للمشروع

### ISSUE THREAD

**Issue by al7jy99** [drupalsaudi/saudi-distribution#21]
صورة الخطوات

**Comment by al7jy99** [comment]
![dd (2)](https://user-images.githubusercontent.com/36070864/103155201-6340ba00-47ae-11eb-84e3-63c589fca98d.png)

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
