### ISSUE TITLE
Animate Any

### ISSUE THREAD

**Issue by al7jy99** [drupalsaudi/saudi-distribution#23]
https://www.drupal.org/project/animate_any

**Comment by al7jy99** [comment]
@shabib-m

**Comment by shabib-m** [comment]
https://github.com/drupalsaudi/saudi-distribution/commit/a7cab5506d686dea5fa0862ed1e2a847a5089476
https://github.com/drupalsaudi/saudi-distribution/commit/81a8f70643a49c2601d455b43467082e8f59f6a0
