### ISSUE TITLE
للمساهمه في التوزيعه

### ISSUE THREAD

**Issue by shabib-m** [drupalsaudi/saudi-distribution#25]
السلام عليكم ورحمة الله وبركاته 
هذي بذره لحصر كل اللي نحتاجه حتى نسهل على المنضمين الجدد تحديد اللي يرغبون فيه 

في التصميم =

1- تصميم المواقع : 
بحاجه الى مبدعين لاضافة لمساتهم من ناحية تصميم الواجهه ولوحة التحكم ومبدعين في 
UX لتحسين تجربة المستخدم 

2- تصميم جرافكس : 
بحاجة الى تصميم شعار وبنرات وبروشورات وايقونات خاصه بالتوزيعه 

في المحتوى =

1- مسار التعليم : 
بحاجه الى دروس وشروحات من تثبيت التوزيعه الى ادارتها ان كان صور ونص او شرح فيديو لاضافتها للويكي وتسهيل التعامل معها

2- مسار الترجمه : 
بالامكان المساهمه في ترجمة التوزيعه هنا او من ضمن مجموعة ترجمة دروبال العربية

3- مسار اضافة المحتوى : 
حاليا نحتاج الى اضافة محتوى للتوزيعه حتى يكون فيه مثال مباشر لها بعد تثبيت التوزيعه

كل اللي نحتاجه منكم دقايق بسيطه منكم بتضيف للمشروع الكثير اللي هو في النهاية مجاني مفتوح المصدر ومنكم ولكم 
حتى الاقتراحات والاستفسارات مرحب بها 

ملاحظه : المساهمه لا يشترط فيها الانظمام لفريق التطوير و التقيد والالتزام بشروط انجاز المهام مع حفظ حقوق المساهمين ومساهماتهم وعرضها في مكانها المناسب ونشرها للكل

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
