### ISSUE TITLE
تصميم صفحة مجلس الادارة

### ISSUE THREAD

**Issue by shabib-m** [drupalsaudi/saudi-distribution#30]
pc
![board-of-directors-1](https://user-images.githubusercontent.com/66571723/105536526-8bfe9580-5d01-11eb-9232-611c4b862c47.png)

ipad
![board-of-directors-2](https://user-images.githubusercontent.com/66571723/105536549-9325a380-5d01-11eb-94a4-310f8d6feea3.png)

mobile
![board-of-directors-3](https://user-images.githubusercontent.com/66571723/105536578-a173bf80-5d01-11eb-91f5-186aae249506.png)

https://github.com/drupalsaudi/saudi-distribution/pull/29

**Comment by shabib-m** [comment]
@balharthi

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
