### ISSUE TITLE
اضافات محرر النصوص ckeditor

### ISSUE THREAD

**Issue by shabib-m** [drupalsaudi/saudi-distribution#34]
### وصف المهمة
هذي البذره بحاجه الى مساهماتكم 
محرر النصوص المعروف في دروبال تنقصه بعض الادوات المناسبه واللي اعتقد انها مطلوبه في الغالب 
هذي بعض الوحدات المناسبة =

السماح بتعديل لون الخطوط
https://www.drupal.org/project/colorbutton

تغيير وتنسيق الخط والحجم
https://www.drupal.org/project/ckeditor_font

السماح للمحرر بإضافة روابط بخصائص متعددة مثل فتح الصفحة في نافذة جديدة
https://www.drupal.org/project/anchor_link

### النتيجة المتوقعة
تركيب وضبط إعدادات الوحدات المذكورة في الوصف وأن تعمل بشكل سليم في المحرر.

### لكي يتم إعتبار هذه المهمة مكتملة

- [ ] تركيب وتفعيل وحدة [CKEditor Color Button](https://www.drupal.org/project/colorbutton)
- [ ] تركيب وتفعيل وحدة [CKEditor Font Size and Family](https://www.drupal.org/project/ckeditor_font)
- [ ] تركيب وتفعيل وحدة [CKEditor Anchor Link](https://www.drupal.org/project/ckeditor_font)

والتأكد من رفعها في إعدادات البروفايل

**Comment by samaphp** [comment]
هذه المهمة اكتملت وتم قبول طلب السحب PR
