### ISSUE TITLE
تصميم الصفحات الداخلية

### ISSUE THREAD

**Issue by shabibalm** [drupalsaudi/saudi-distribution#35]
هنا بيكون باذن الله جمع تصاميم الصفحات الداخلة مع تحديدها حتى نفتح المجال 
للمبدعين اللي حابين يساهمون معنا 

صفحة مجلس الادارة 
https://github.com/drupalsaudi/saudi-distribution/issues/30

صفحة المناسبة والفعالية (لايوجد تعليقات بها)
![تصميم-المناسبات-والفعاليات](https://user-images.githubusercontent.com/45591694/112042488-9e0d8080-8b58-11eb-92c4-43551c2447cb.png)

----

صفحة المحاضر 
- [x] إصلاح مشكلة الصورة بحيث تكون إما على اليمين والكتابة تحيط بها. أو توسيط الصورة بشكل مناسب
![تصميم-صفحة-المحاضر](https://user-images.githubusercontent.com/45591694/112042621-c85f3e00-8b58-11eb-89a3-b94fdf349b98.png)

صفحة عضو مجلس الادارة
- [x] إخفاء اسم المؤلف والتاريخ
- [x] إلغاء صورة كاتب المحتوى (المربع الصغير)
- [x] تحسين طريقة عرض صورة العضو نفسه، يتم إضافة نمط جديد يتم فيه تحديد العرض والارتفاع 
![تصميم-صفحة-عضو-مجلس-الادارة](https://user-images.githubusercontent.com/45591694/112042839-0b211600-8b59-11eb-8e96-96dec53d46cb.png)

صفحة المقال
- [x] توسيط الصورة بشكل مناسب
![تصميم-صفحة-المقال](https://user-images.githubusercontent.com/45591694/112043010-3a378780-8b59-11eb-82e4-ec76ae3ce549.png)

باقي روابط القائمة العلوية هل تحتاج اضافة روابط او لا
![روابط-القائمة](https://user-images.githubusercontent.com/45591694/112043214-7a970580-8b59-11eb-86b7-0455511d9b05.png)

الملفات الشخصية هل تحتاج الى تصميم خاص بها؟

**Comment by samaphp** [comment]
ماشاء الله، جميل الله يعافيك، تم التحقق من التعديلات
