### ISSUE TITLE
مراجعة المهام المفتوحة وتصنيفها وإغلاقها

### ISSUE THREAD

**Issue by samaphp** [drupalsaudi/saudi-distribution#36]
هذه المهمة الهدف منها هو مراجعة المهام القديمة وتصنيفها بإستخدام الـ Labels ثم إغلاقها عند الحاجة للإغلاق

سأقوم بتحديث هذه المهمة وإضافة المهام التي تم إغلاقها وتفاصيلها

**Comment by samaphp** [comment]
المهمة رقم #1 : تم تحديدها بتصنيف [توثيق](https://github.com/drupalsaudi/saudi-distribution/labels/documentation) وتصنيف [تحسين](https://github.com/drupalsaudi/saudi-distribution/labels/enhancement)
لأنها تحتوي على معلومات مهمة حول سياسة إختيار الوحدات البرمجية وأيضاً بعض الإقتراحات الإضافية.

المهمة رقم #2 : تم إغلاقها بسبب أن الهدف منها كان خطة عمل وحيث أنها بتاريخ قديم فأعتقد أن الحاجة لها لم تعد قائمة حالياً.

المهمة رقم #4 : تم تحديدها بتصنيف [توثيق](https://github.com/drupalsaudi/saudi-distribution/labels/documentation) لأنها تحتوي على تفاصيل ومعلومات حول مزايا النسخة الأولى للتوزيعة

المهمة رقم #6 : تم تحديدها بتصنيف [غير مكتملة](https://github.com/drupalsaudi/saudi-distribution/labels/incomplete) لأنها تبدو كانت لمهام قديمة عامة قد تكون غير مكتملة

المهمة رقم #7 : تم إغلاقها حيث أن الهدف منها كان لتوثيق مساهمة الحضور في أحد الاجتماعات.

المهمة رقم #8 : تم إغلاقها بسبب أنها مهمة كان الغرض منها هو تخطيط نموذج التصميم المبدئي لصفحات الموقع. ويبدو أن الحاجة منها قد انتهت الآن.

المهمة رقم #9 : تم إغلاقها لأن الهدف منها كان لجمع أفكار تصميم شعار التوزيعة وقد تم رفع شعار التوزيعة واختياره في اجتماعات سابقة. لذا الهدف من هذه المهمة قد انتهى.

المهمة رقم #10 تم تحديدها بتصنيف [غير مكتملة](https://github.com/drupalsaudi/saudi-distribution/labels/incomplete) حيث أنها تحتوي على ملفات مرفقة للقالب الإداري المقترح. ولكن يبدو أن القالب الإداري لم يعد أولوية حالياً.

المهمة رقم #11 : الهدف منها هو توزيع فرق العمل في فترة سابقة.

المهمة رقم #12 : تم تحديدها بتصنيف [غير مكتملة](https://github.com/drupalsaudi/saudi-distribution/labels/incomplete) حيث أنها تحتوي على بعض المهام الفرعية التي يبدو أنها لم تكتمل حتى الآن. وتم إغلاق المهمة لأنها قديمة وقد تكون انتفت الحاجة من المهام المتبقية.

المهمة رقم #13 : تم تحديدها بتصنيف [توثيق](https://github.com/drupalsaudi/saudi-distribution/labels/documentation) حيث أنه كان الهدف منها هو إضافة روابط لبعض المواد التعليمية وتوثيقها.

المهمة رقم #16 : تم تصنيفها بتصنيف [توثيق](https://github.com/drupalsaudi/saudi-distribution/labels/documentation) وإغلاقها حيث أنها كانت تصف بعض التحديثات التي تمت على التوزيعة

المهمة رقم #17 : تم إغلاقها حيث أنها كانت تصف بعض التحديثات التي تمت على التوزيعة

المهمة رقم #18 : تم تحديدها بتصنيف [توثيق](https://github.com/drupalsaudi/saudi-distribution/labels/documentation) وتصنيف [تحسين](https://github.com/drupalsaudi/saudi-distribution/labels/incomplete) حيث أنها تحتوي على وصف لبعض الوظائف التي تم عملها للتوزيعة وأيضاً تحتوي على بعض النقاط التي قد تكون لاتزال لم تكتمل.

المهمة رقم #19 : تم تحديدها بتصنيف [توثيق](https://github.com/drupalsaudi/saudi-distribution/labels/documentation) حيث أنه كان الهدف منها هو إضافة روابط لبعض المواد التعليمية وتوثيقها.

المهمة رقم #20 : تم تحديدها بتصنيف [توثيق](https://github.com/drupalsaudi/saudi-distribution/labels/documentation) حيث أن على مايبدو أنها تصف هيكل فريق العمل.

المهمة رقم #21 : تم تحديدها بتصنيف [توثيق](https://github.com/drupalsaudi/saudi-distribution/labels/documentation) حيث أن على مايبدو أنها تصف إجراء الإنضمام للمساهمة بطريقة محددة.

المهمة رقم #22 : تم إغلاقها حيث أنها لاتحتوي على وصف وغير واضحة.

المهمة رقم #25 : تم تحديدها بتصنيف [توثيق](https://github.com/drupalsaudi/saudi-distribution/labels/documentation) وإغلاقها حيث أنها تحتوي على معلومات مهمة للتوثيق.

المهمة رقم #30 : تم إغلاقها حيث أنها لاتحتوي على وصف وعلى مايبدو أن المطلوب من التصميم قد تم تنفيذه حسب الصور المرفقة في نفس المهمة.

----

هناك بعض المهام التي تم إغلاقها وتحديدها بتصنيف [غير مكتملة](https://github.com/drupalsaudi/saudi-distribution/labels/incomplete)
أقترح مراجعتها بشكل سريع ومساعدتي في معرفة الذي يحتاج إلى إعادة فتح مجدداً وإكمال العمل.

سيتم إغلاق هذه المهمة بعد أسبوع من الآن في حال لاتوجد تعليقات

**Comment by shabib-m** [comment]
هذي المهمة https://github.com/drupalsaudi/saudi-distribution/issues/30
مرتبطه pulls https://github.com/drupalsaudi/saudi-distribution/pull/29
