### ISSUE TITLE
الاصدار الاول للتوزيعه

### ISSUE THREAD

**Issue by shabib-m** [drupalsaudi/saudi-distribution#4]
مميزات التوزيعه في الاصدار الاول لها  والموجود فيها 

تثبيت التوزيعه ما تحتاجون الى اختيار اللغه او اختيار التوزيعه مجرد الدخول على ملف التثبيت ينقلكم الى تثبيت التوزيعه مباشرة وتم اختيار اللغه العربية بشكل افتراضي مع الوقت التابع للرياض و الدوله المملكة العربية السعودية وهذا يختصر عليكم خطوات عند التثبيت

1. انواع المحتوى 

- الصفحه الاساسية للصفحات الثابته في الموقع مثل (عن الموقع)

- المقال خاص بالاخبار والمقالات للموقع

- المحاضر ومقدم الفعالية والمناسبة (معلومات عنه حتى يتم اضافتها الى  الفعالية)

- الفعالية والمناسبة بالامكان اضافة الصور وتنسيق نص الفعالية باستخدام محرر متطور واضافة المحاضر ومقدم الفعالية والمناسبة بكل سهولة

- البحث خاص باضافة البحوث العلمية داخل الموقع 

- الكتب بالامكان اضافة الكتب المناسبه واللي من انتاج الجمعية او التابعه لاعضاء الجمعية (تدعم اغلب صيغ ملفات الكتب وبالامكان التعديل واضافة اي صيغه جديده للملفات من لوحة التحكم بدون تدخل برمجي)

- اعضاء مجلس الاداره تضم حقول مهمه اسم العضو وصورته ومعلومات عنه مع المسمى وكلها ممكن التعديل عليها من لوحة التحكم 

ملاحظة : ميزة السهوله والتحكم في اضافة الحقول وطريقة عرض المحتوى من لوحة التحكم بالامكان الكل يتعامل معها مطور او مستخدم نهائي , ميزة التحكم في نشر المحتوى او بقائه غير منشور حتى يراجعه احت مجموعات الاعضاء , ميزة التحكم في الصلاحيات الممنوحه لمجموعات الاعضاء بالامكان التحكم في اضافة وتعديل وحذف المحتوى لكل مجموعه من مجموعات الاعضاء 

2. مجموعات الاعضاء 

-  موجود في التوزيعه ثلاث مجموعات افتراضية (مستخدم مجهول الزوار)  و (الاعضاء) و (الادارة معها كامل الصلاحيات )

- تم اضافة مجموعه جديدة من مجموعات الاعضاء خاصه باعضاء الجمعية وهذه مفيده في تحديد الصلاحيات وتحديد فئات هذه المجموعه مع امكانية اضافة مسمياتها داخل الملفات الشخصية والمحتوى التابع لها وايضا بالامكان مراسلة هذه المجموعه عن طريق البريد الاكتروني واخبارهم بالمناسبات والفعاليات القادمه وجديد محتوى الجمعية وايضا لطلب المشاركه في الاستفتاء و الاستبيان 

3. نموذج خاص بتسجيل اعضاء الجمعية منفصل عن نموذج التسجيل الافتراضي الخاص بادارة  واعضاء الموقع مجرد الدخول عليه واكمال البيانات ينضاف العضو الى مجموعة اعضاء الجمعية مباشرة بدون تدخل من ادارة الموقع 

4. اضافة نظام التحقق من الزائر في النماذج التالية لمنع السبام وعدم اغراق الموقع بطلفات الروبوتات 

- اتصل بنا للموقع

- اتصل بنا للاعضاء

- تسجيل الاعضاء

- تسجيل الدخول

- تسجيل اعضاء الجمعية

هذا الموجود حاليا والمميزات والاضافات قالبه للتعديل والاضافه في اي وقت ستجدون تاريخ مقابل كل اضافة جديدة

**Comment by shabib-m** [comment]
تعمل توزيعة الجمعيات (احد مشاريع مجموعة دروبال السعودية) على نظام دروبال المجاني والمفتوح المصدر والمدعوم عالميا من مختلف دول العالم نظرا لدعمها وتطويرها المستمر وتقديم امكانيات وتقنيات مميزه تم اختيارها لاستخدامها كمنصه لتوزيعة الجمعيات وحتى نقدم الفائده لمجتمعنا التقني مع تقديم الدعم التقني من قبل مجتمع دروبال السعودية ...

مميزات دروبال = 

1- المجانية بالامكان تحميل دروبال وتثبيت واستخدامها والتطوير عليها بدون دفع رسوم لها 
2- تعمل على برامج مجانية خادم apache ( وغيره مثل nginx), قواعد البيانات mysql (وغيرها postgreSQL,SQLite), تعمل مع نسخ 7.4 واعلى من لغة البرمجة php

3- مجتمع ضخم من المطورين يقفون خلف استمرار تطوير دروبال وانتاجاتهم تشهد على ابداعاتهم لتسهيل حياة المطورين والمستخدم النهائي لها 

4- خبره 20 سنه من بداية طرح دروبال عام 2000 م الى اليوم وهي مستمره في تقديم الامكانيات ومتابعة التطور الحاصل في مجال التحكم وادارة المحتوى في مواقع الانترنت 

5- الدعم المستمر للنظام من قبل المجتمع يتكفلون بترقيع الثغرات الامنية واصلاح الاخطاء واضافة المميزات 

6- تعمل تحت رخصة استخدام معروفه GPL 

7- قلة تكلفة المشروع بشكل عام وتشغيله بشكل خاص 

8- تقديم الادوات المناسبة للمطورين حتى تسهل عليهم حياتهم وتختصر عليهم الوقت في التطوير

مميزات توزيعة الجمعيات =

1- انواع المحتوى المتوفره في التوزيعه (صفحات, مقالات واخبار, الفعالية والمناسبة, المحاضر ومقدم الفعالية والمناسبه, بحث, عرض الشرائح ( سلايد شو ), عضو مجلس الاداره, كتب) مع الحقول المناسبة لكل نوع من انواع المحتوى ان حقل لرفع الصور او حقل لرفع الملفات او حقول نصية  او حقول خاصه مثل حقل البحث عن المحاضر من داخل نموذج اضافة المناسبة ….

2- التحكم في التسجيل واضافة صفحة خاصه بتسجيل اعضاء الجمعيات مع اضافتهم مباشرة لمجموعه خاص بهم من ضمن مجموعات الاعضاء وايضا التحكم في اضافة الحقول المناسبة عند تسجيل الزوار في الموقع 

3- امكانية اضافة مجموعات للاعضاء بعدد لا نهائي 

4- التحكم في الصلاحيات على حسب مجموعة العضو بالامكان السماح لاي مجموعة من اضافة المحتوى لنوع واحد من انواع المحتوى ومنعها من اخرى وتشمل اضافة المحتوى او التعديل عليه او حذف المحتوى مع خيارات اخرى مثل امكانية الدخول على لوحة التحكم والتعامل مع الخيارات الموجوده بها 

5- جميع الاضافات الموجوده في التوزيعه يتم دعمها من مجتمع دروبال وهذا يضمن لكم الاستمرارية وعدم ضياع محتوى الجمعيات ومجهوداتكم 
6- امكانية تطويع التوزيعه لتخصصات اخرى والمرونه في تطويرها في اي وقت 

7- امكانية اضافة منتجات خاصه للشركات كاضافة منتج محاسبي او ادارة موظفين وغيرها بكل سهولة والاستفادة منها

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
