### ISSUE TITLE
خطأ عدم وجود ملف custom_rtl.css و مع cdn integrity و crossorigin

### ISSUE THREAD

**Issue by shabib-m** [drupalsaudi/saudi-distribution#42]
موجود خطا موجود في القالب مع دعم rtl و ltr 

بعد تفعيل pr https://github.com/drupalsaudi/saudi-distribution/pull/26

مطلوب اضافة ملفين فارغين داخل القالب 
css/custom_rtl.css
css/custom_ltr.css

وايضا خطا عدم اضافة 
integrity + crossorigin

للقالب الموجود هنا 
https://rtlcss.com/cdn/css-frameworks/bootstrap/

للفائدة 
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by samaphp** [comment]
جميل بارك الله فيك، تم التحقق من التعديل
