### ISSUE TITLE
ضبط الروابط العلوية وربطها بمحتويات

### ISSUE THREAD

**Issue by samaphp** [drupalsaudi/saudi-distribution#43]
حالياً الروابط في أعلى الموقع لاترتبط بمحتويات مباشرة

- [x] ربط زر عن الجمعية بصفحة من نوع (الصفحة الأساسية) ويكون محتوى هذه الصفحة (نص تجريبي).
- [x] ربط زر أقسام الجمعية بصفحة من نوع (الصفحة الأساسية) ويكون محتوى هذه الصفحة (نص تجريبي).
- [x] ربط زر دعم الجمعية بصفحة من نوع (الصفحة الأساسية) ويكون محتوى هذه الصفحة (نص تجريبي).
- [x] المركز الإعلامي: صفحة فيو تعرض قائمة المقالات في جدول يظهر بها اسم المقال وعمود آخر لتاريخ النشر

**Comment by shabib-m** [comment]
حقل اسم المحاضر
![الفعالية والمناسبة-اسم المحاضر](https://user-images.githubusercontent.com/66571723/114331718-4eb1e300-9b4d-11eb-8eb6-599672158a9b.png)

**Comment by samaphp** [comment]
@shabib-m 

بعد مراجعة الدمج التابعة لهذه المهمة يبدو أن بعض التعديلات التي تمت لم تظهر بشكل صحيح، وهذه هي التعديلات التي تمت مراجعتها:

- [x] ظهور اسم المحاضر بشكل جميل وإيقونة جديدة <img width="225" alt="Screen Shot 2021-05-03 at 4 35 38 AM" src="https://user-images.githubusercontent.com/531627/116835129-daa5b080-abc9-11eb-86e2-3594bf49f1a0.png">

- [x] ظهور محتوى في صفحة أقسام الجمعية
- [ ] صفحة المساعدة

حيث كما يظهر من الملف التالي أن صفحة المساعدة لاتزال تعرض المحتوى القديم، بالرغم من أنه قد تم تعديل الملف التالي:

https://github.com/drupalsaudi/saudi-distribution/blob/e1d304016fadb7c54302593423ef93cc35eef693/profiles/drupalsaudi/config/install/simple_block.simple_block.block_sample_test.yml

بالمحتوى الجديد .. ولكن الملف الذي يتم عرضه فعلياً في صفحة المساعدة هو الملف التالي:

https://github.com/drupalsaudi/saudi-distribution/blob/e1d304016fadb7c54302593423ef93cc35eef693/profiles/drupalsaudi/config/install/block.block.blwkmsadttwzytdrwbalalswdytsample.yml

وهو كما يتضح لايزال بالمحتوى القديم

**Comment by samaphp** [comment]
تم التأكيد على حل الإشكالية المذكورة في التعليق السابق في الدمج رقم [54](https://github.com/drupalsaudi/saudi-distribution/pull/54)

وبهذا تكون صفحة المساعدة حالياً يتم عرضها بالمحتوى الجديد

شكراً لك @shabib-m
