### ISSUE TITLE
لائحه الاقتراحات 

### ISSUE THREAD

**Issue by shabib-m** [drupalsaudi/saudi-distribution#6]
- [ ] ترجمة الواجهه للتوزيعه
- [ ] مصممين الجرافكس (شعار للتوزيعه نستخدمه في القالب للتوزيعه وعلى منشوراتنا يفضل استخدام eps ai)

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
