### ISSUE TITLE
SAAD project- Meeting Agendas - July 12, 2020

### ISSUE THREAD

**Issue by raedkhurayji** [drupalsaudi/saudi-distribution#7]
Attendees الحضور
- شبيب الدوسري
- يسري عبدالوهاب
- عبدالله الحجي 
- رائد الخريجي
- نواف آل حسين
- عبدالعزيز الصفدي
- رغد عاتي 
- جواهر المسعود

Agenda  الاجنده

- تجربة نسخة المطورين وكتابة الملاحظات في issues المشروع 
- توزيع المهام والأدوار لفريق عمل التوزيعة
- الهيكله الرئيسيه للجمعيات قبل لا نبدأ ديزاين لازم يكون جاهز
- الهيكل الخاص بالصفحات + الصفحات الداخليه 
- الهدف بناء مجتمع تقني تتوفر لديه مهارات عالية
- مناقشة ماتم تنفيذة من قبل الاعضاء خلال الاسبوع الماضي 
- ضرورية توزيع الفرق (البزنس-الديزاين-التطوير- الترجمه ،...)
- اقتراح رفع نسخه لايف ( لتسهيل التعديل عليها من قبل فريق المحتوى)
- تحديد بذرة العمل الاساسية ( لغة عربية جيدة - الخدمات الأساسية التي تستفيد منها معظم الجمعيات ) 
- مبادرة قادرون لتحقيق موضوع الاستدامه المالية 
- اقتراح بوضع اجندة الاجتماعات الاسبوعية القادمة ( لاختصار الوقت والانجاز )
- تقديم خطة للدعم ( مسارات التعليم)
- تم إضافة محتوى جديد خاص بأعضاء مجلس الإدارة
- https://github.com/drupalsaudi/saudi-distribution/issues/10 إضافة قالب إدارة يسمح ب(إضافة التعديلات- إضافة المحتوى- إضافة الروابط وتنسيقها ) بحيث تكون منفصله عن قالب الإدارة الافتراضي ليسهل تحديث النسخة.
- عمل برانش لاضافة بعض التخصصات 
- توضيح المهارات بتريلو لمعرفة فريق العمل

**Comment by raedkhurayji** [comment]
Attended

**Comment by ghost** [comment]
Attended..

**Comment by shabib-m** [comment]
Attended

**Comment by al7jy99** [comment]
Attended

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
