### ISSUE TITLE
Prototype النموذج المبدئي 

### ISSUE THREAD

**Issue by raedkhurayji** [drupalsaudi/saudi-distribution#8]
النموذج المبدئي لشكل الموقع 

1- https://drive.google.com/open?id=14SsJ-ojiVfIL0pqPxVvas9h-jlQG5qEs
2- https://drive.google.com/open?id=1hIKibCXSy56WjiUr3UJ97k3946q5GQzu
3- https://drive.google.com/open?id=1hkHVLi5aofiZpoFi7P1-a455epDeyE-5
4- https://drive.google.com/open?id=1ISfMN9UEB0bWqeRsmxz-pET6I0WP9aZe
5- https://drive.google.com/open?id=1_BFrF20ee-e58qxJ2MD6K2YxxOtpNjl1
6- https://drive.google.com/open?id=1Ff0FrvRUyCmxVbdbQE_5le4IH1YiRLps
7- https://drive.google.com/open?id=1icIJR6pMWMTumzY5Gw9VGDIGCVXTMFu1
8- https://drive.google.com/open?id=1dWe1l5zuKz29P0fyrupwdfUD-kdkamPY

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب

ملاحظة/ بعض الصور تتطلب صلاحيات وصول لمشاهدة الصور. أقترح إرفاقها هنا مباشرة أفضل.
