### ISSUE TITLE
Distro logo شعار التوزيعه

### ISSUE THREAD

**Issue by raedkhurayji** [drupalsaudi/saudi-distribution#9]
شعار التوزيعة

**Comment by al7jy99** [comment]
![image](https://user-images.githubusercontent.com/36070864/87408875-cbb72880-c5cc-11ea-9118-44132ce6ec1f.png)

**Comment by al7jy99** [comment]
الفكرة الاولى @Raghady

**Comment by shabib-m** [comment]
![11دروبال السعودية](https://user-images.githubusercontent.com/66571723/87430137-75a6ad00-c5ed-11ea-821d-3ffd895d63ce.png)

**Comment by al7jy99** [comment]
[Uploading SAAD_logo (1).pdf…]()

**Comment by shabib-m** [comment]
![logo-saad-1](https://user-images.githubusercontent.com/66571723/104122818-5ac4b380-5358-11eb-9640-9d481e185558.png)

![logo-saad](https://user-images.githubusercontent.com/66571723/104122824-60ba9480-5358-11eb-8109-53bbbe8d149b.png)

**Comment by shabib-m** [comment]
بدون اليد 😄 
![logo-saad_0](https://user-images.githubusercontent.com/66571723/104137465-ee749f00-53ad-11eb-8409-31b808b96bf5.png)

**Comment by shabib-m** [comment]
فكرة @al7jy99 
![logo-saad-face-smile](https://user-images.githubusercontent.com/66571723/104137473-0a784080-53ae-11eb-8f78-386162bb15f4.png)

**Comment by samaphp** [comment]
تم إغلاق المهمة يرجى مراجعة المهمة رقم #36 للتعرف على الأسباب
